site_name: DEQAR Documentation
### document structure ###
pages:
    - Home: index.md
    - Architecture and Data Model: DEQAR_overview.md
    - Data Submission:
        - Data preparation: submission_object_fields.md
        - Pipeline: data_submission.md
        - Methods:
            - Webform: webform.md
            - CSV Upload: csv_upload.md
            - REST API: submission_api.md
#    - Data administration:
    - Search and discovery:
        - Web interface: public_web.md
        - WebAPI: web_api.md
### theme configuration ###
theme:
    name: readthedocs
    custom_dir: theme/
extra_css: [ "css/deqar.css" ]
markdown_extensions:
    - toc:
        permalink: True

