site_name: DEQAR Documentation
### document structure ###
nav:
    - Home: index.md
    - Quick Start Guide: quick_start_guide.md
    - Architecture and Data Model: architecture_data_model.md
    - Data Submission: data_submission.md
    - Search and Discovery: web_api.md
### theme configuration ###
theme:
    name: readthedocs
    collapse_navigation: true
extra_css: [ "css/deqar.css" ]
markdown_extensions:
    - toc:
        permalink: True

