site_name: DEQAR Documentation
### document structure ###
pages:
    - Home: index.md
    - Architecture and Data Model: DEQAR_overview.md
    - Data Submission: data_submission_overview.md
#    - Data administration:
    - Search and discovery:
        - Web interface: public_web.md
        - Web API: web_api.md
### theme configuration ###
theme:
    name: readthedocs
    custom_dir: theme/
extra_css: [ "css/deqar.css" ]
markdown_extensions:
    - toc:
        permalink: True

