site_name: DEQAR Documentation
### document structure ###
nav:
    - Home: index.md
    - quick_start_guide.md
    - architecture_data_model.md
    - Submitting data:
        - institution_data.md
        - report_data.md
        - data_submission.md
    - Web API:
        - web_api_intro.md
        - web_api_auth.md
        - web_api_endpoints.md
        - web_api_examples.md
    - Integrations:
        - europass.md
### theme configuration ###
theme:
    name: readthedocs
    collapse_navigation: true
extra_css: [ "css/deqar.css" ]
plugins:
    - search
    - mermaid2:
        arguments:
          er:
            minEntityHeight: 35
          theme: base
          themeVariables:
            primaryColor: '#f3f6f6'
            primaryTextColor: '#404040'
            primaryBorderColor: '#033163'
            lineColor: '#033163'

markdown_extensions:
    - footnotes
    - toc:
        permalink: True

