site_name: DEQAR Documentation
pages:
    - Home: index.md
    - Data Model: data_model.md
    - Data Submission Workflow: data_submission.md
    - Submission Object Fields: 'submission_object_fields.md'
    - CSV Upload: csv_upload.md
    - Submission API: submission_api.md
theme: readthedocs
